#include "web_html.h"

/**
 * HTML page for vehicle configuration
 * Separated for easy maintenance and customization
 */
const char* config_html_page = 
    "<!DOCTYPE html>"
    "<html lang='en'>"
    "<head>"
    "    <meta charset='UTF-8'>"
    "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "    <title>Vehicle GPS Tracker - Configuration</title>"
    "    <style>"
    "        * {"
    "            margin: 0;"
    "            padding: 0;"
    "            box-sizing: border-box;"
    "        }"
    "        body {"
    "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
    "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
    "            min-height: 100vh;"
    "            display: flex;"
    "            align-items: center;"
    "            justify-content: center;"
    "            padding: 20px;"
    "        }"
    "        .container {"
    "            background: white;"
    "            max-width: 450px;"
    "            width: 100%;"
    "            padding: 40px 30px;"
    "            border-radius: 15px;"
    "            box-shadow: 0 10px 40px rgba(0,0,0,0.2);"
    "            animation: slideIn 0.5s ease-out;"
    "        }"
    "        @keyframes slideIn {"
    "            from {"
    "                opacity: 0;"
    "                transform: translateY(-20px);"
    "            }"
    "            to {"
    "                opacity: 1;"
    "                transform: translateY(0);"
    "            }"
    "        }"
    "        .header {"
    "            text-align: center;"
    "            margin-bottom: 30px;"
    "        }"
    "        .header h1 {"
    "            color: #333;"
    "            font-size: 28px;"
    "            margin-bottom: 10px;"
    "        }"
    "        .header .subtitle {"
    "            color: #666;"
    "            font-size: 14px;"
    "        }"
    "        .icon {"
    "            font-size: 60px;"
    "            margin-bottom: 20px;"
    "        }"
    "        .form-group {"
    "            margin-bottom: 25px;"
    "        }"
    "        label {"
    "            display: block;"
    "            color: #555;"
    "            font-weight: 600;"
    "            margin-bottom: 8px;"
    "            font-size: 14px;"
    "        }"
    "        input[type='text'] {"
    "            width: 100%;"
    "            padding: 14px 16px;"
    "            border: 2px solid #e0e0e0;"
    "            border-radius: 8px;"
    "            font-size: 16px;"
    "            transition: all 0.3s;"
    "            text-transform: uppercase;"
    "        }"
    "        input[type='text']:focus {"
    "            outline: none;"
    "            border-color: #667eea;"
    "            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);"
    "        }"
    "        .hint {"
    "            font-size: 12px;"
    "            color: #999;"
    "            margin-top: 5px;"
    "        }"
    "        button {"
    "            width: 100%;"
    "            padding: 16px;"
    "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
    "            color: white;"
    "            border: none;"
    "            border-radius: 8px;"
    "            font-size: 16px;"
    "            font-weight: 600;"
    "            cursor: pointer;"
    "            transition: all 0.3s;"
    "            text-transform: uppercase;"
    "            letter-spacing: 1px;"
    "        }"
    "        button:hover {"
    "            transform: translateY(-2px);"
    "            box-shadow: 0 5px 20px rgba(102, 126, 234, 0.4);"
    "        }"
    "        button:active {"
    "            transform: translateY(0);"
    "        }"
    "        button:disabled {"
    "            background: #ccc;"
    "            cursor: not-allowed;"
    "            transform: none;"
    "        }"
    "        .status {"
    "            margin-top: 20px;"
    "            padding: 15px;"
    "            border-radius: 8px;"
    "            text-align: center;"
    "            font-weight: 500;"
    "            display: none;"
    "        }"
    "        .status.show {"
    "            display: block;"
    "            animation: fadeIn 0.3s;"
    "        }"
    "        @keyframes fadeIn {"
    "            from { opacity: 0; }"
    "            to { opacity: 1; }"
    "        }"
    "        .status.success {"
    "            background: #d4edda;"
    "            color: #155724;"
    "            border: 1px solid #c3e6cb;"
    "        }"
    "        .status.error {"
    "            background: #f8d7da;"
    "            color: #721c24;"
    "            border: 1px solid #f5c6cb;"
    "        }"
    "        .status.loading {"
    "            background: #d1ecf1;"
    "            color: #0c5460;"
    "            border: 1px solid #bee5eb;"
    "        }"
    "        .spinner {"
    "            display: inline-block;"
    "            width: 20px;"
    "            height: 20px;"
    "            border: 3px solid rgba(255,255,255,0.3);"
    "            border-radius: 50%;"
    "            border-top-color: white;"
    "            animation: spin 1s linear infinite;"
    "            margin-right: 10px;"
    "            vertical-align: middle;"
    "        }"
    "        @keyframes spin {"
    "            to { transform: rotate(360deg); }"
    "        }"
    "        .info-box {"
    "            background: #f8f9fa;"
    "            padding: 15px;"
    "            border-radius: 8px;"
    "            margin-top: 20px;"
    "            font-size: 13px;"
    "            color: #666;"
    "        }"
    "        .info-box strong {"
    "            color: #333;"
    "        }"
    "    </style>"
    "</head>"
    "<body>"
    "    <div class='container'>"
    "        <div class='header'>"
    "            <div class='icon'>🚗</div>"
    "            <h1>Vehicle GPS Tracker</h1>"
    "            <p class='subtitle'>Initial Configuration Setup</p>"
    "        </div>"
    "        "
    "        <form id='configForm'>"
    "            <div class='form-group'>"
    "                <label for='vehicle_id'>Vehicle ID / Plate Number</label>"
    "                <input "
    "                    type='text' "
    "                    id='vehicle_id' "
    "                    name='vehicle_id' "
    "                    placeholder='e.g., B1234ABC' "
    "                    required "
    "                    pattern='[A-Za-z0-9]+'"
    "                    maxlength='20'"
    "                    autocomplete='off'"
    "                    autofocus"
    "                >"
    "                <div class='hint'>Enter the vehicle plate number or unique identifier</div>"
    "            </div>"
    "            "
    "            <button type='submit' id='submitBtn'>"
    "                Save Configuration"
    "            </button>"
    "        </form>"
    "        "
    "        <div id='status' class='status'></div>"
    "        "
    "        <div class='info-box'>"
    "            <strong>Note:</strong> After saving, the device will restart automatically. "
    "            You will need to reconnect to access the device."
    "        </div>"
    "    </div>"
    "    "
    "    <script>"
    "        const form = document.getElementById('configForm');"
    "        const statusDiv = document.getElementById('status');"
    "        const submitBtn = document.getElementById('submitBtn');"
    "        const vehicleInput = document.getElementById('vehicle_id');"
    "        "
    "        function showStatus(message, type) {"
    "            statusDiv.textContent = message;"
    "            statusDiv.className = 'status ' + type + ' show';"
    "        }"
    "        "
    "        function setLoading(loading) {"
    "            submitBtn.disabled = loading;"
    "            if (loading) {"
    "                submitBtn.innerHTML = '<span class=\"spinner\"></span>Saving...';"
    "            } else {"
    "                submitBtn.innerHTML = 'Save Configuration';"
    "            }"
    "        }"
    "        "
    "        form.addEventListener('submit', function(e) {"
    "            e.preventDefault();"
    "            "
    "            const vehicleId = vehicleInput.value.trim().toUpperCase();"
    "            "
    "            if (!vehicleId) {"
    "                showStatus('Please enter a vehicle ID', 'error');"
    "                return;"
    "            }"
    "            "
    "            if (!/^[A-Z0-9]+$/.test(vehicleId)) {"
    "                showStatus('Vehicle ID must contain only letters and numbers', 'error');"
    "                return;"
    "            }"
    "            "
    "            setLoading(true);"
    "            showStatus('Saving configuration...', 'loading');"
    "            "
    "            const xhr = new XMLHttpRequest();"
    "            xhr.open('POST', '/save', true);"
    "            xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');"
    "            "
    "            xhr.onload = function() {"
    "                setLoading(false);"
    "                "
    "                if (xhr.status === 200) {"
    "                    showStatus('✓ Configuration saved successfully!', 'success');"
    "                    vehicleInput.disabled = true;"
    "                    "
    "                    setTimeout(function() {"
    "                        showStatus('Device is restarting...', 'loading');"
    "                    }, 1500);"
    "                    "
    "                    setTimeout(function() {"
    "                        showStatus('✓ Setup complete! You can now close this page.', 'success');"
    "                    }, 4000);"
    "                } else {"
    "                    showStatus('✗ Error saving configuration. Please try again.', 'error');"
    "                }"
    "            };"
    "            "
    "            xhr.onerror = function() {"
    "                setLoading(false);"
    "                showStatus('✗ Network error. Please check your connection.', 'error');"
    "            };"
    "            "
    "            xhr.send('vehicle_id=' + encodeURIComponent(vehicleId));"
    "        });"
    "        "
    "        // Auto-convert to uppercase"
    "        vehicleInput.addEventListener('input', function() {"
    "            this.value = this.value.toUpperCase();"
    "        });"
    "    </script>"
    "</body>"
    "</html>";